DROP DATABASE IF EXISTS Pt03_Alex_Ruiz;
CREATE DATABASE IF NOT EXISTS Pt03_Alex_Ruiz;
USE Pt03_Alex_Ruiz;

CREATE TABLE articles (
    id INT AUTO_INCREMENT PRIMARY KEY,
    titol VARCHAR(100) NOT NULL,
    cos TEXT NOT NULL
);
